name: build-push-img
on:  
  push:
    branches:
      - main
jobs:
  build-push-image:
    runs-on: ubuntu-latest
    steps:
      -
        name: checkout repo
        uses: actions/checkout@v4

      - 
        name: login to dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - 
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/github_actions_img:latest